import { Weight } from "lucide-react";
import "./globals.css";
import { Assistance } from 'next/font/google'

const assistanceFont = {
  Weight: ['400', '500', '600', '700', '800'],
  subsets: ['latin'],
  display: 'swap'
}

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${assistanceFont.className}antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
