import "./globals.css";
import { Assistant } from "next/font/google";
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";

const assistanceFont = Assistant({
  weight: ["400", "500", "600", "700", "800"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${assistanceFont.className} antialiased`}>
        <ToastContainer position="top-right" autoClose={5000} />
        {children}
      </body>
    </html>
  );
}